#!/bin/sh

### this script is used to shutdown/undefine domain with remove all attached disks

# if input arg is domain id, need transfer into domain name
if [ ! $(virsh list --all --name | grep  "^$1$") ];then
  domain_name=$(virsh list | awk -v id=$1 '$1 == id {print $2}')
  arg1=${1:+"$domain_name"}
  # reset args
  set -- $arg1
fi

echo "Destroy: $1"
virsh destroy $1 2> /dev/null

for disk_path in $(virt-query $1 disks | awk '{print $3}'); do
	pool=$(virsh vol-pool $disk_path)
	name=$(virsh vol-info $disk_path | awk '$1 == "Name:" {print $2}')
	
	echo "Delete volume: $disk ($name in $pool)"
	virsh vol-delete $name $pool
done

echo "Undefine: $1"
virsh undefine $1
