#!/bin/sh

### this script is used to shutdown/undefine domain with remove all attached disks

# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")

## use domain name instead of domain id
domain_name=$(virsh list | awk -v id=$1 '$1 == id {print $2}')
arg1=${1:+"$domain_name"}
# reset args
set -- $arg1

echo "Destroy: $1"
virsh destroy $1 2> /dev/null

for disk_path in $("$SCRIPTPATH"/virt-query $1 disks | awk '{print $3}'); do
	pool=$(virsh vol-pool $disk_path)
	name=$(virsh vol-info $disk_path | awk '$1 == "Name:" {print $2}')
	
	echo "Delete volume: $disk ($name in $pool)"
	virsh vol-delete $name $pool
done

echo "Undefine: $1"
virsh undefine $1

